'use client';

import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { Download, Edit3, Save, X, Eye } from 'lucide-react';

interface AuditViewProps {
    initialAnalysis: string;
    monthLabel: string;
    totalIncome: number;
    totalExpense: number;
    profit: number;
    monthParam: string;
}

const AuditView = ({ initialAnalysis, monthLabel, totalIncome, totalExpense, profit, monthParam }: AuditViewProps) => {
    const [isEditing, setIsEditing] = useState(false);
    const [editedAnalysis, setEditedAnalysis] = useState(initialAnalysis);

    const handlePrint = () => {
        window.print();
    };

    return (
        <>
            {/* STICKY ACTION BAR */}
            <div className="fixed top-8 left-1/2 -translate-x-1/2 z-[100] print:hidden">
                <div className="bg-white/90 backdrop-blur-2xl border border-slate-200/60 shadow-[0_20px_50px_rgba(0,0,0,0.15)] rounded-full px-4 py-2 flex items-center gap-2">
                    <button 
                        onClick={handlePrint}
                        className="flex items-center gap-2 px-6 py-2.5 bg-[#0F172A] hover:bg-blue-600 text-white rounded-full transition-all text-sm font-bold shadow-lg active:scale-95"
                    >
                        <Download size={16} />
                        Download PDF
                    </button>
                    
                    <div className="w-px h-6 bg-slate-200 mx-2" />
                    
                    {!isEditing ? (
                        <button 
                            onClick={() => setIsEditing(true)}
                            className="flex items-center gap-2 px-6 py-2.5 bg-white border border-slate-200 hover:border-blue-400 hover:text-blue-600 text-slate-600 rounded-full transition-all text-sm font-bold active:scale-95"
                        >
                            <Edit3 size={16} />
                            Edit Report
                        </button>
                    ) : (
                        <div className="flex items-center gap-1">
                            <button 
                                onClick={() => setIsEditing(false)}
                                className="flex items-center gap-2 px-6 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-full transition-all text-sm font-bold shadow-lg active:scale-95"
                            >
                                <Save size={16} />
                                Finish Editing
                            </button>
                            <button 
                                onClick={() => {
                                    setEditedAnalysis(initialAnalysis);
                                    setIsEditing(false);
                                }}
                                className="p-2.5 text-rose-500 hover:bg-rose-50 rounded-full transition-all"
                                title="Reset & Cancel"
                            >
                                <X size={20} />
                            </button>
                        </div>
                    )}
                </div>
            </div>

            <div className="max-w-[1000px] mx-auto overflow-hidden bg-white shadow-2xl print:shadow-none my-10 print:my-0 transition-all duration-500">
                
                {/* --- PAGE 1: REFINED COVER PAGE --- */}
                <div className="h-[1414px] w-full relative flex flex-col justify-between p-24 bg-[#0F172A] text-white">
                    <div className="flex items-center gap-4">
                        <div className="w-10 h-10 bg-[#3B82F6] rounded-xl flex items-center justify-center text-white text-xl font-black">S</div>
                        <span className="text-xl font-bold tracking-tighter">SnapSchool Intelligence</span>
                    </div>
                    
                    <div className="space-y-10">
                        <div className="h-0.5 w-16 bg-[#3B82F6]" />
                        <div className="space-y-4">
                            <span className="text-xs font-bold uppercase tracking-[0.6em] text-[#94A3B8]">Confidential Executive Review</span>
                            <h1 className="text-8xl font-outfit font-black leading-[0.95] tracking-tight">
                                Fiscal Performance Report 
                            </h1>
                            <h2 className="text-5xl font-outfit font-light text-[#3B82F6] italic">— {monthLabel}</h2>
                        </div>
                        <p className="text-xl text-[#94A3B8] font-medium max-w-2xl leading-relaxed">
                            A comprehensive multi-dimensional audit of school operations, financial liquidity, and growth roadmap generated by SnapAssistant AI.
                        </p>
                    </div>

                    <div className="flex justify-between items-end border-t border-white/10 pt-12">
                        <div className="space-y-2">
                            <p className="text-[10px] font-black text-white/40 uppercase tracking-[0.5em]">Authority Level</p>
                            <p className="text-sm font-bold uppercase tracking-widest text-[#3B82F6]">Tier 1 Administration</p>
                        </div>
                        <div className="text-right space-y-1">
                            <p className="text-sm font-bold">SnapSchool Global Operations</p>
                            <p className="text-xs text-white/40 italic">Date generated: {new Date().toLocaleDateString()}</p>
                        </div>
                    </div>
                </div>

                {/* --- PAGE 2: EXECUTIVE SUMMARY --- */}
                <div className="min-h-[1414px] w-full px-24 py-24 bg-white">
                    <div className="flex justify-between items-center mb-20 pb-8 border-b border-slate-100">
                        <h2 className="text-3xl font-outfit font-black text-[#0F172A] tracking-tight">Financial Summary</h2>
                        <div className="px-4 py-1.5 bg-slate-50 rounded-full border border-slate-100">
                            <span className="text-[10px] font-black text-[#64748B] uppercase tracking-[0.3em]">{monthLabel} Audit</span>
                        </div>
                    </div>

                    {/* KPI CARDS (PREMIUM) */}
                    <div className="grid grid-cols-3 gap-6 mb-20">
                        <div className="p-8 bg-gradient-to-br from-[#F8FAFC] to-[#F1F5F9] rounded-[40px] border border-slate-100/50 shadow-sm space-y-4">
                            <div className="flex items-center gap-2">
                                <span className="p-2 bg-emerald-50 text-emerald-600 rounded-lg text-lg">💰</span>
                                <span className="text-[10px] font-black text-[#64748B] uppercase tracking-widest">Revenue</span>
                            </div>
                            <p className="text-4xl font-outfit font-black text-[#0F172A] tracking-tighter">${totalIncome.toLocaleString()}</p>
                            <div className="flex items-center gap-2">
                                <span className="text-[10px] font-bold text-emerald-600 bg-emerald-100/50 px-2 py-0.5 rounded-full">↑ Healthy Vol.</span>
                            </div>
                        </div>
                        <div className="p-8 bg-gradient-to-br from-[#F8FAFC] to-[#F1F5F9] rounded-[40px] border border-slate-100/50 shadow-sm space-y-4">
                            <div className="flex items-center gap-2">
                                <span className="p-2 bg-rose-50 text-rose-600 rounded-lg text-lg">📉</span>
                                <span className="text-[10px] font-black text-[#64748B] uppercase tracking-widest">Expenses</span>
                            </div>
                            <p className="text-4xl font-outfit font-black text-[#0F172A] tracking-tighter">${totalExpense.toLocaleString()}</p>
                            <div className="flex items-center gap-2">
                                <span className="text-[10px] font-bold text-slate-400 bg-slate-100 px-2 py-0.5 rounded-full">Operational Costs</span>
                            </div>
                        </div>
                        <div className="p-8 bg-[#0F172A] rounded-[40px] shadow-2xl shadow-blue-950/20 space-y-4 text-white">
                            <div className="flex items-center gap-2">
                                <span className="p-2 bg-blue-500/20 text-blue-400 rounded-lg text-lg">⚖️</span>
                                <span className="text-[10px] font-black text-white/40 uppercase tracking-widest text-blue-100/60">Net Profit</span>
                            </div>
                            <p className="text-4xl font-outfit font-black text-white tracking-tighter">${profit.toLocaleString()}</p>
                            <div className="h-1.5 w-full bg-white/10 rounded-full overflow-hidden">
                                <div className="h-full bg-blue-400 w-[70%] transition-all" />
                            </div>
                        </div>
                    </div>

                    {/* AI ANALYSIS CONTENT START */}
                    <div className="prose prose-slate max-w-none">
                        <div className="space-y-12 text-slate-800">
                            {isEditing ? (
                                <div className="space-y-4 animate-in fade-in duration-300">
                                    <div className="flex items-center justify-between bg-blue-50 p-4 rounded-xl border border-blue-100">
                                        <div className="flex items-center gap-3 text-blue-700">
                                            <Edit3 size={20} />
                                            <span className="font-bold text-sm uppercase tracking-widest">Editorial Mode Active</span>
                                        </div>
                                        <span className="text-[10px] text-blue-400 font-medium italic">Changes are temporary for this print session</span>
                                    </div>
                                    <textarea 
                                        value={editedAnalysis}
                                        onChange={(e) => setEditedAnalysis(e.target.value)}
                                        className="w-full h-[800px] p-10 bg-slate-50 border-2 border-dashed border-slate-200 rounded-3xl font-mono text-base focus:ring-4 focus:ring-blue-100 focus:border-blue-400 transition-all outline-none"
                                        placeholder="Enter markdown analysis here..."
                                    />
                                </div>
                            ) : (
                                <ReactMarkdown 
                                    components={{
                                        h3: ({node, ...props}) => (
                                            <div className="mt-20 mb-8 flex items-center gap-4 bg-blue-50/50 p-4 rounded-xl border-l-4 border-blue-500">
                                                <h3 className="text-xl font-outfit font-black text-[#1E3A8A] uppercase tracking-tight" {...props} />
                                                <div className="h-px grow bg-blue-100" />
                                            </div>
                                        ),
                                        p: ({node, ...props}) => <p className="text-lg leading-relaxed text-[#334155] font-medium mb-8" {...props} />,
                                        ul: ({node, ...props}) => <ul className="list-none space-y-4 mb-8 pl-0" {...props} />,
                                        ol: ({node, ...props}) => <ol className="list-decimal space-y-10 mb-8 pl-8 marker:text-[#3B82F6] marker:font-black" {...props} />,
                                        li: ({node, ...props}) => (
                                            <li className="relative flex items-start gap-4">
                                                {(node as any)?.parent?.tagName === 'ul' && (
                                                    <div className="mt-2.5 w-1.5 h-1.5 rounded-full bg-[#3B82F6] shrink-0" />
                                                )}
                                                <div className="flex flex-col gap-1">
                                                    <span className="text-[#334155] font-medium leading-relaxed">{props.children}</span>
                                                </div>
                                            </li>
                                        ),
                                        strong: ({node, children, ...props}) => {
                                            const originalText = String(children);
                                            const text = originalText.replace(/^\[|\]$/g, '').toLowerCase();
                                            const cleanDisplay = originalText.replace(/^\[|\]$/g, '');

                                            if (text.includes("growth") || text.includes("+")) {
                                                return <span className="text-emerald-600 font-bold">{cleanDisplay}</span>;
                                            }
                                            if (text.includes("risk") || text.includes("issue")) {
                                                return <span className="text-rose-600 font-bold">{cleanDisplay}</span>;
                                            }
                                            return <strong className="font-extrabold text-blue-800 bg-blue-50/30 px-1 rounded-sm" {...props}>{cleanDisplay}</strong>;
                                        },
                                        hr: ({node, ...props}) => <hr className="my-16 border-slate-100" {...props} />,
                                        blockquote: ({node, children, ...props}) => (
                                            <div className="p-10 bg-indigo-50/50 border-l-4 border-[#4F46E5] rounded-3xl my-10 shadow-sm relative overflow-hidden">
                                                <div className="absolute top-0 right-0 p-4 opacity-5 text-6xl font-black text-indigo-900">AI</div>
                                                <p className="text-[10px] font-black text-indigo-600 uppercase tracking-[0.4em] mb-4 flex items-center gap-2">
                                                    Strategic Intelligence Recommendation
                                                </p>
                                                <div className="text-lg italic font-medium text-[#1E293B] leading-relaxed">
                                                    {children}
                                                </div>
                                            </div>
                                        )
                                    }}
                                >
                                    {editedAnalysis}
                                </ReactMarkdown>
                            )}
                        </div>
                    </div>
                </div>

                {/* --- FOOTER (REFINED) --- */}
                <div className="px-24 py-16 bg-[#F8FAFC] flex justify-between items-center border-t border-slate-100">
                    <div className="flex items-center gap-8">
                        <div>
                             <p className="text-[9px] font-black text-slate-300 uppercase tracking-[0.4em] mb-3 font-outfit">Approved Signature</p>
                             <div className="w-56 h-px bg-slate-200" />
                        </div>
                    </div>
                    <div className="text-right">
                        <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-2 font-outfit">
                            Audit Reference: SN-AUDIT-{monthParam.toUpperCase()}
                        </p>
                        <p className="text-[8px] font-bold text-slate-200 uppercase tracking-[0.8em] font-outfit">
                            Generated by SnapSchool AI | Senior Intelligence Engine
                        </p>
                    </div>
                </div>
            </div>
            
            <style jsx global>{`
                @media print {
                    @page { margin: 0; size: A4; }
                    body { margin: 0 !important; padding: 0 !important; background: white !important; -webkit-print-color-adjust: exact !important; }
                    .h-[1414px], .min-h-[1414px] { height: 297mm !important; min-height: 297mm !important; page-break-after: always !important; }
                    .shadow-2xl { box-shadow: none !important; }
                    .max-w-[1000px] { max-width: 100% !important; margin: 0 !important; }
                }
                .prose blockquote p { margin: 0 !important; }
            `}</style>
        </>
    );
};

export default AuditView;
