import { Html, Head, Preview, Body, Container, Section, Text, Heading, Row, Column } from "@react-email/components";
import * as React from "react";

interface DailyReportEmailProps {
  date: string;
  financialData: {
    totalIncomeToday: number;
    totalExpensesToday: number;
    netResult: number;
  };
  payments: {
    unpaidStudents: number;
    unpaidTeachers: number;
    unpaidStaff: number;
    totalUnpaidAmount: number;
  };
  activity: {
    incomesAddedToday: number;
    expensesAddedToday: number;
  };
  insights: string[];
}

export const DailyReportEmail = ({
  date,
  financialData,
  payments,
  activity,
  insights,
}: DailyReportEmailProps) => {
  return (
    <Html>
      <Head />
      <Preview>Daily School Report for {date}</Preview>
      <Body style={main}>
        <Container style={container}>
          <Heading style={h1}>SnapSchool Daily Report</Heading>
          <Text style={text}>Date: {date}</Text>

          <Section style={section}>
            <Heading as="h2" style={h2}>📊 Financial Summary</Heading>
            <Row>
              <Column>
                <Text style={statLabel}>Income Today</Text>
                <Text style={{ ...statValue, color: "#10b981" }}>${financialData.totalIncomeToday}</Text>
              </Column>
              <Column>
                <Text style={statLabel}>Expenses Today</Text>
                <Text style={{ ...statValue, color: "#ef4444" }}>${financialData.totalExpensesToday}</Text>
              </Column>
              <Column>
                <Text style={statLabel}>Net</Text>
                <Text style={{ ...statValue, color: financialData.netResult >= 0 ? "#10b981" : "#ef4444" }}>
                  ${financialData.netResult}
                </Text>
              </Column>
            </Row>
          </Section>

          <Section style={section}>
            <Heading as="h2" style={h2}>⚠️ Unpaid Alerts</Heading>
            <Text style={text}>Total Unpaid Amount: <strong style={{ color: "#ef4444" }}>${payments.totalUnpaidAmount}</strong></Text>
            <ul style={list}>
              <li style={listItem}>{payments.unpaidStudents} Students are unpaid.</li>
              <li style={listItem}>{payments.unpaidTeachers} Teachers are unpaid.</li>
              <li style={listItem}>{payments.unpaidStaff} Staff members are unpaid.</li>
            </ul>
          </Section>

          <Section style={section}>
            <Heading as="h2" style={h2}>📈 Activity</Heading>
            <ul style={list}>
              <li style={listItem}>{activity.incomesAddedToday} incomes recorded today.</li>
              <li style={listItem}>{activity.expensesAddedToday} expenses recorded today.</li>
            </ul>
          </Section>

          <Section style={section}>
            <Heading as="h2" style={h2}>🧠 Smart Insights</Heading>
            {insights.map((insight, idx) => (
              <div key={idx} style={insightCard}>
                <Text style={insightText}>💡 {insight}</Text>
              </div>
            ))}
          </Section>

          <Text style={footer}>
            Auto-generated by zbiba • SnapSchool AI Layer
          </Text>
        </Container>
      </Body>
    </Html>
  );
};

export default DailyReportEmail;

const main = {
  backgroundColor: "#f6f9fc",
  fontFamily:
    '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
};

const container = {
  backgroundColor: "#ffffff",
  margin: "0 auto",
  padding: "20px 0 48px",
  marginBottom: "64px",
  borderRadius: "12px",
  boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
  maxWidth: "600px",
  marginTop: "40px",
};

const section = {
  padding: "0 48px",
  marginBottom: "24px",
};

const h1 = {
  color: "#4f46e5",
  fontSize: "24px",
  fontWeight: "bold",
  textAlign: "center" as const,
  padding: "0 48px",
};

const h2 = {
  color: "#333",
  fontSize: "18px",
  fontWeight: "bold",
  borderBottom: "2px solid #f0f0f0",
  paddingBottom: "8px",
};

const text = {
  color: "#525f7f",
  fontSize: "16px",
  lineHeight: "24px",
  textAlign: "center" as const,
};

const statLabel = {
  color: "#8898aa",
  fontSize: "12px",
  textTransform: "uppercase" as const,
  fontWeight: "bold",
};

const statValue = {
  fontSize: "20px",
  fontWeight: "bold",
  margin: "0",
};

const list = {
  color: "#525f7f",
  fontSize: "14px",
  paddingLeft: "20px",
};

const listItem = {
  marginBottom: "8px",
};

const insightCard = {
  backgroundColor: "#f0fdf4",
  border: "1px solid #bbf7d0",
  padding: "16px",
  borderRadius: "8px",
  marginBottom: "12px",
};

const insightText = {
  color: "#166534",
  margin: 0,
  fontSize: "14px",
  fontWeight: "500",
};

const footer = {
  color: "#8898aa",
  fontSize: "12px",
  marginTop: "48px",
  textAlign: "center" as const,
};
