import React from 'react';
import { getFinancialReportData, getAIFinancialReport } from '../../actions';
import ReactMarkdown from 'react-markdown';

export const dynamic = "force-dynamic";

const AuditPage = async ({ params }: { params: { month: string } }) => {
    // month will be like "April_2026"
    const monthLabel = decodeURIComponent(params.month).replace('_', ' ');
    
    let report;
    let aiAnalysis;
    let error = null;

    try {
        report = await getFinancialReportData(monthLabel);
        aiAnalysis = await getAIFinancialReport(report);
    } catch (e: any) {
        error = e.message;
    }

    if (error || !report) {
        return (
            <div className="p-20 text-center">
                <h1 className="text-2xl font-bold text-rose-500">Audit Generation Failed</h1>
                <p className="text-slate-500 mt-2">{error || "Could not retrieve report data."}</p>
            </div>
        );
    }

    const totalIncome = report.metrics.totalTuitionIncome + report.incomeBreakdown.reduce((acc, curr) => acc + curr.amount, 0);
    const totalExpense = report.metrics.totalSalaryExpenses + report.metrics.totalGeneralExpenses;
    const profit = totalIncome - totalExpense;

    return (
        <div className="bg-[#F1F5F9] min-h-screen text-[#1E293B] font-inter">
            {/* Fonts: Modern & Professional */}
            <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
            
            {/* Auto-print script */}
            <script dangerouslySetInnerHTML={{ __html: `window.onload = () => { setTimeout(() => window.print(), 1500); }` }} />
            
            <div className="max-w-[1000px] mx-auto overflow-hidden bg-white shadow-2xl print:shadow-none my-10 print:my-0">
                
                {/* --- PAGE 1: REFINED COVER PAGE --- */}
                <div className="h-[1414px] w-full relative flex flex-col justify-between p-24 bg-[#0F172A] text-white">
                    <div className="flex items-center gap-4">
                        <div className="w-10 h-10 bg-[#3B82F6] rounded-xl flex items-center justify-center text-white text-xl font-black">S</div>
                        <span className="text-xl font-bold tracking-tighter">SnapSchool Intelligence</span>
                    </div>
                    
                    <div className="space-y-10">
                        <div className="h-0.5 w-16 bg-[#3B82F6]" />
                        <div className="space-y-4">
                            <span className="text-xs font-bold uppercase tracking-[0.6em] text-[#94A3B8]">Confidential Executive Review</span>
                            <h1 className="text-8xl font-outfit font-black leading-[0.95] tracking-tight">
                                Fiscal Performance Report 
                            </h1>
                            <h2 className="text-5xl font-outfit font-light text-[#3B82F6] italic">— {monthLabel}</h2>
                        </div>
                        <p className="text-xl text-[#94A3B8] font-medium max-w-2xl leading-relaxed">
                            A comprehensive multi-dimensional audit of school operations, financial liquidity, and growth roadmap generated by SnapAssistant AI.
                        </p>
                    </div>

                    <div className="flex justify-between items-end border-t border-white/10 pt-12">
                        <div className="space-y-2">
                            <p className="text-[10px] font-black text-white/40 uppercase tracking-[0.5em]">Authority Level</p>
                            <p className="text-sm font-bold uppercase tracking-widest text-[#3B82F6]">Tier 1 Administration</p>
                        </div>
                        <div className="text-right space-y-1">
                            <p className="text-sm font-bold">SnapSchool Global Operations</p>
                            <p className="text-xs text-white/40 italic">Date generated: {new Date().toLocaleDateString()}</p>
                        </div>
                    </div>
                </div>

                {/* --- PAGE 2: EXECUTIVE SUMMARY --- */}
                <div className="min-h-[1414px] w-full px-24 py-24 bg-white">
                    <div className="flex justify-between items-center mb-20 pb-8 border-b border-slate-100">
                        <h2 className="text-3xl font-outfit font-black text-[#0F172A] tracking-tight">Financial Summary</h2>
                        <div className="px-4 py-1.5 bg-slate-50 rounded-full border border-slate-100">
                            <span className="text-[10px] font-black text-[#64748B] uppercase tracking-[0.3em]">{monthLabel} Audit</span>
                        </div>
                    </div>

                    {/* KPI CARDS (PREMIUM) */}
                    <div className="grid grid-cols-3 gap-6 mb-20">
                        <div className="p-8 bg-[#F8FAFC] rounded-[40px] border border-slate-100/50 shadow-sm space-y-4">
                            <div className="flex items-center gap-2">
                                <span className="p-2 bg-emerald-50 text-emerald-600 rounded-lg text-lg">💰</span>
                                <span className="text-[10px] font-black text-[#64748B] uppercase tracking-widest">Revenue</span>
                            </div>
                            <p className="text-4xl font-outfit font-black text-[#0F172A] tracking-tighter">${totalIncome.toLocaleString()}</p>
                            <div className="flex items-center gap-2">
                                <span className="text-[10px] font-bold text-emerald-600 bg-emerald-100/50 px-2 py-0.5 rounded-full">↑ Healthy Vol.</span>
                            </div>
                        </div>
                        <div className="p-8 bg-[#F8FAFC] rounded-[40px] border border-slate-100/50 shadow-sm space-y-4">
                            <div className="flex items-center gap-2">
                                <span className="p-2 bg-rose-50 text-rose-600 rounded-lg text-lg">📉</span>
                                <span className="text-[10px] font-black text-[#64748B] uppercase tracking-widest">Expenses</span>
                            </div>
                            <p className="text-4xl font-outfit font-black text-[#0F172A] tracking-tighter">${totalExpense.toLocaleString()}</p>
                            <div className="flex items-center gap-2">
                                <span className="text-[10px] font-bold text-slate-400 bg-slate-100 px-2 py-0.5 rounded-full">Operational Costs</span>
                            </div>
                        </div>
                        <div className="p-8 bg-[#0F172A] rounded-[40px] shadow-2xl shadow-blue-950/20 space-y-4 text-white">
                            <div className="flex items-center gap-2">
                                <span className="p-2 bg-blue-500/20 text-blue-400 rounded-lg text-lg">⚖️</span>
                                <span className="text-[10px] font-black text-white/40 uppercase tracking-widest text-blue-100/60">Net Profit</span>
                            </div>
                            <p className="text-4xl font-outfit font-black text-white tracking-tighter">${profit.toLocaleString()}</p>
                            <div className="h-1.5 w-full bg-white/10 rounded-full overflow-hidden">
                                <div className="h-full bg-blue-400 w-[70%] transition-all" />
                            </div>
                        </div>
                    </div>

                    {/* AI ANALYSIS CONTENT START */}
                    <div className="prose prose-slate max-w-none">
                        <div className="space-y-12 text-slate-800">
                            <ReactMarkdown 
                                components={{
                                    h3: ({node, ...props}) => (
                                        <div className="mt-20 mb-8 flex items-center gap-4">
                                            <h3 className="text-2xl font-outfit font-black text-[#0F172A] uppercase tracking-tight" {...props} />
                                            <div className="h-px grow bg-slate-100" />
                                        </div>
                                    ),
                                    p: ({node, ...props}) => <p className="text-lg leading-relaxed text-[#334155] font-medium mb-8" {...props} />,
                                    ul: ({node, ...props}) => <ul className="list-none space-y-4 mb-8 pl-0" {...props} />,
                                    ol: ({node, ...props}) => <ol className="list-decimal space-y-10 mb-8 pl-8 marker:text-[#3B82F6] marker:font-black" {...props} />,
                                    li: ({node, ...props}) => (
                                        <li className="relative flex items-start gap-4">
                                            {/* Detect if parent is ul to add a custom bullet (casting to any to avoid lint) */}
                                            {(node as any)?.parent?.tagName === 'ul' && (
                                                <div className="mt-2.5 w-1.5 h-1.5 rounded-full bg-[#3B82F6] shrink-0" />
                                            )}
                                            <div className="flex flex-col gap-1">
                                                <span className="text-[#334155] font-medium leading-relaxed">{props.children}</span>
                                            </div>
                                        </li>
                                    ),
                                    strong: ({node, children, ...props}) => {
                                        const text = String(children).toLowerCase();
                                        if (text.includes("growth") || text.includes("+")) {
                                            return <span className="text-emerald-600 font-bold">{children}</span>;
                                        }
                                        if (text.includes("risk") || text.includes("issue")) {
                                            return <span className="text-rose-600 font-bold">{children}</span>;
                                        }
                                        return <strong className="font-bold text-[#0F172A] border-b-2 border-indigo-50" {...props}>{children}</strong>;
                                    },
                                    hr: ({node, ...props}) => <hr className="my-16 border-slate-100" {...props} />,
                                    blockquote: ({node, children, ...props}) => (
                                        <div className="p-10 bg-slate-50/50 border-l-4 border-[#3B82F6] rounded-2xl my-10 shadow-sm relative overflow-hidden">
                                            <div className="absolute top-0 right-0 p-4 opacity-5 text-6xl font-black">AI</div>
                                            <p className="text-[10px] font-black text-[#3B82F6] uppercase tracking-[0.4em] mb-4 flex items-center gap-2">
                                                Strategic Intelligence Insight
                                            </p>
                                            <div className="text-lg italic font-medium text-[#1E293B] leading-relaxed">
                                                {children}
                                            </div>
                                        </div>
                                    )
                                }}
                            >
                                {aiAnalysis}
                            </ReactMarkdown>
                        </div>
                    </div>
                </div>

                {/* --- FOOTER (REFINED) --- */}
                <div className="px-24 py-16 bg-[#F8FAFC] flex justify-between items-center border-t border-slate-100">
                    <div className="flex items-center gap-8">
                        <div>
                             <p className="text-[9px] font-black text-slate-300 uppercase tracking-[0.4em] mb-3 font-outfit">Approved Signature</p>
                             <div className="w-56 h-px bg-slate-200" />
                        </div>
                    </div>
                    <div className="text-right">
                        <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-2 font-outfit">
                            Audit Reference: SN-AUDIT-{params.month.toUpperCase()}
                        </p>
                        <p className="text-[8px] font-bold text-slate-200 uppercase tracking-[0.8em] font-outfit">
                            Generated by SnapSchool AI | Senior Intelligence Engine
                        </p>
                    </div>
                </div>
            </div>
            
            <style dangerouslySetInnerHTML={{ __html: `
                @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=Inter:wght@400;500;600;700;800;900&display=swap');
                
                .font-outfit { font-family: 'Outfit', sans-serif; }
                .font-inter { font-family: 'Inter', sans-serif; }
                
                @media print {
                    @page { margin: 0; size: A4; }
                    body { margin: 0 !important; padding: 0 !important; background: white !important; -webkit-print-color-adjust: exact !important; }
                    .no-print { display: none !important; }
                    .h-[1414px], .min-h-[1414px] { height: 297mm !important; min-height: 297mm !important; page-break-after: always !important; }
                    .shadow-2xl { box-shadow: none !important; }
                    .max-w-[1000px] { max-width: 100% !important; margin: 0 !important; }
                    .bg-[#0F172A] { background-color: #0F172A !important; -webkit-print-color-adjust: exact; }
                }
                
                .prose blockquote p { margin: 0 !important; }
                body { line-height: 1.6; letter-spacing: -0.01em; }
            `}} />
        </div>
    );
};

export default AuditPage;
